version: '3.8'

services:
  web:
    build:
      context: ./gestor # Asegúrate de que esta ruta sea correcta para tu sistema
      dockerfile: Dockerfile
    container_name: gestor_web
    ports:
      - "80:80" # Mapea el puerto 80 del host al puerto 80 del contenedor
    volumes:
      - ./gestor:/var/www/html # Mapea tu carpeta de la aplicación al contenedor
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mapea la configuración de Nginx
    depends_on:
      - db
    networks:
      - gestor_network

  db:
    image: postgres:16 # Puedes usar una versión específica de PostgreSQL
    environment:
      POSTGRES_DB: gestor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ale2025
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persistencia de datos de la base de datos
      - /home/polipruebas/gestor/gestor.sql:/docker-entrypoint-initdb.d/gestor.sql
    networks:
      - gestor_network

  jenkins:
      build:
          context: .
          dockerfile: Dockerfile.jenkins
      user: root
      ports:
        - "8080:8080"
        - "5000:5000"
      volumes:
        - jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - DOCKER_HOST=unix:///var/run/docker.sock
      container_name: ci_jenkins
      networks:
        - gestor_network
    
networks:
  gestor_network:
    driver: bridge

volumes:
  db_data:
  jenkins_home:
