services:
  web:
    image: nginx:latest
    ports:
      - "8082:8080"
    volumes:
      - ./gestor:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db
      - php-fpm
    networks:
      - gestor_network

  php-fpm:
    build:
      context: ./gestor
      dockerfile: Dockerfile.php
    volumes:
      - ./gestor:/var/www/html:rw
    networks:
      - gestor_network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: gestor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ale2025
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - /home/polipruebas/gestor/gestor.sql:/docker-entrypoint-initdb.d/gestor.sql
    networks:
      - gestor_network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root
    ports:
      - "8081:8080"
      - "5000:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

networks:
  gestor_network:
    driver: bridge

volumes:
  db_data:
  jenkins_home:
