services:
  web:
    build:
      context: ./gestor # Asegúrate de que esta ruta sea correcta para tu sistema
    image: nginx:latest
    ports:
      - "80:80" # Mapea el puerto 80 del host al puerto 80 del contenedor
    volumes:
      - ./gestor:/var/www/html # Mapea tu carpeta de la aplicación al contenedor
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mapea la configuración de Nginx
      - ./default.conf:/etc/nginx/sites-available/default.conf
    depends_on:
      - db
      - php-fpm
    networks:
      - gestor_network

  php-fpm:
    build:
      context: ./gestor
      dockerfile: Dockerfile.php
    volumes:
      - ./gestor:/var/www/html:rw
    networks:
      - gestor_network

  db:
    image: postgres:16 # Puedes usar una versión específica de PostgreSQL
    environment:
      POSTGRES_DB: gestor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ale2025
    container_name: mi-postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persistencia de datos de la base de datos
      - ./gestor/gestor.sql:/docker-entrypoint-initdb.d/gestor.sql
    networks:
      - gestor_network

networks:
  gestor_network:
    driver: bridge

volumes:
  db_data:
